### ISSUE TITLE
"Couldn't create project file"

### ISSUE THREAD

**Issue by nwtn** [uliwitness/stackimport#3]
Whenever I try to use stackimport, I get this same error message:

````
dnewton@MacBook-Pro ~/Downloads 👍  stackimport --dumprawblocks HyperTalk\ QuickRef
Error: Couldn't create project file at 'HyperTalk QuickRef.xstk/project.xml'
Error: Conversion of 'HyperTalk QuickRef' incomplete/failed.
````

This happens no matter which flags I use, which stack I try to import, or what directory I'm in.

Any thoughts? Thanks

**Comment by uliwitness** [comment]
On 30 Aug 2015, at 21:48, David Newton <notifications@github.com> wrote:
> Whenever I try to use stackimport, I get this same error message:
> 
> dnewton@MacBook-Pro ~/Downloads 👍  stackimport --dumprawblocks HyperTalk\ QuickRef
> Error: Couldn't create project file at 'HyperTalk QuickRef.xstk/project.xml'
> Error: Conversion of 'HyperTalk QuickRef' incomplete/failed.
> 
> This happens no matter which flags I use, which stack I try to import, or what directory I'm in.
> 
> Any thoughts? Thanks

Pass in the full pathname, then it should work.

Cheers,
-- Uli Kusterer
"The Witnesses of TeachText are everywhere..."
http://stacksmith.org

**Comment by nwtn** [comment]
Awesome, that worked. Thanks!
